version: '2'
services:
    slackrepo-app:
        image: slackrepo
        external_links:
            - slackrepo-cassandra:cassandra
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_CASSANDRA_CONTACTPOINTS=cassandra
            - JHIPSTER_SLEEP=30 # gives time for the cassandra cluster to start and execute the migration scripts
        ports:
            - 8080:8080
    slackrepo-cassandra:
        extends:
            file: cassandra-cluster.yml
            service: slackrepo-cassandra
    slackrepo-cassandra-node:
        image: cassandra:2.2.7
        links:
            - slackrepo-cassandra:seed
        environment:
            - CASSANDRA_SEEDS=seed
    slackrepo-cassandra-migration:
        extends:
            file: cassandra-migration.yml
            service: slackrepo-cassandra-migration
        links:
            - slackrepo-cassandra
        environment:
            - CREATE_KEYSPACE_SCRIPT=create-keyspace-prod.cql
